"""Public metric API for the classification benchmark."""

from .base import EvaluationRecord, Metric, MetricResult
from .calibration import (
    AdaptiveECEMetric,
    MulticlassBrierScoreMetric,
    MulticlassLogLossMetric,
    TopLabelECEMetric,
    adaptive_ece_score,
    multiclass_brier_score,
    multiclass_log_loss_score,
    top_label_ece_score,
)
from .classification import (
    AccuracyMetric,
    MacroF1Metric,
    accuracy_score,
    macro_f1_score,
)
from .evaluator import (
    DEFAULT_METRICS,
    evaluate_jsonl,
    evaluate_records,
    evaluation_record_from_mapping,
    from_classification_records,
    load_evaluation_records,
    results_as_dict,
    write_results_json,
)
from .operational import (
    CostPer1000Metric,
    LatencyP50Metric,
    LatencyP99Metric,
    MeanLatencyMetric,
    TotalCostMetric,
    cost_per_1000_usd,
    latency_percentile_ms,
    mean_latency_ms,
    percentile,
    total_cost_usd,
)

__all__ = [
    "AccuracyMetric",
    "AdaptiveECEMetric",
    "CostPer1000Metric",
    "DEFAULT_METRICS",
    "EvaluationRecord",
    "LatencyP50Metric",
    "LatencyP99Metric",
    "MacroF1Metric",
    "MeanLatencyMetric",
    "Metric",
    "MetricResult",
    "MulticlassBrierScoreMetric",
    "MulticlassLogLossMetric",
    "TopLabelECEMetric",
    "TotalCostMetric",
    "accuracy_score",
    "adaptive_ece_score",
    "cost_per_1000_usd",
    "evaluate_jsonl",
    "evaluate_records",
    "evaluation_record_from_mapping",
    "from_classification_records",
    "latency_percentile_ms",
    "load_evaluation_records",
    "macro_f1_score",
    "mean_latency_ms",
    "multiclass_brier_score",
    "multiclass_log_loss_score",
    "percentile",
    "results_as_dict",
    "top_label_ece_score",
    "total_cost_usd",
    "write_results_json",
]
